name: first-workflow-actions

on: 
  workflow_dispatch:

jobs:   
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step 1"
      - name: step2
        run: echo "step 2"

  job2:
    name: Cowsays
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Ship
        uses: mscoutermarsh/cowsays-action@v1
        with:
          text: ""
          color: blue
